version: '3.8'

services:
  web:
    build: .
    container_name: open-license-media
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./migrations:/app/migrations
    environment:
      - SECRET_KEY=your-secret-key-replace-in-production
      - DATABASE_URI=sqlite:///app.db
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 