name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate static documentation
      run: |
        # Here you can generate static documentation or project website
        mkdir -p public
        cp README.md public/index.md
        cp DOCKER_SETUP.md public/
        
    - name: Setup GitHub Pages
      uses: actions/configure-pages@v3
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public
        branch: gh-pages 